[drink_info]
name = "HTA Build"
build_file_version = "1"

[git]
url = ""
branch = "master"
full_clean_build = false

use_internal_build_file = "" # Uses the build file in the git project. If this option is used all options below this are ignored.

[build_ops]
wrk_dir = "" # Based off of the git created directory.
clean_before_build = [
]

[build_cmds]
test = [ # These cmds must exit with a code 0 for the build to be started.
]
cmds = [
    "",
    ""
]

# These add options may not override options in the scb.toml file.
[add_path]
all = [
]
windows = [
]
linux = [
]
macos = [
]

[add_env] # PROJECT_NAME, BUILD_FILE_VERSION, BUILD_COUNT, BUILD_START_TIME

[alias]
