[options]
git_update_timer = 15 # In minutes.
parallel_builds = false # This could break certin build processes. Could also overwhelm stuff. #TODO Implement!

[process]
windows = "pwsh /c" # Options: cmd /c, pwsh /c, or others (If pwsh is installed and on the path)
linux = ""
macos = ""

drinks = [
    "git_build_hta.toml"
]

[add_path]
all = [
]
windows = [
]
linux = [
]
macos = [
]

[add_env] # SCB_VERSION, BUILD_TRIGGER_TIME

[alias] # This replaces anything in the command. #TODO Implement!
